<?php

/**
 * @file
 * Defines the core Commerce addressfield entity type.
 */
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_operation().
 *
 * Add devel link if this entity type is /commerce_addressfield[_type]/.
 */
function commerce_addressfield_entity_operation(EntityInterface $entity) {
  $operations = array();
  if (!\Drupal::moduleHandler()->moduleExists('devel')) {
    return $operations;
  }

}
